# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

image:
  - Visual Studio 2022
#  - Ubuntu2204

version: 0.7.2-build-0{build}

pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmd: powershell .\build.ps1 --target=Pack
  - sh: nuget locals all -clear
  - sh: dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:net6.0
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.snupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: S4K9NB29VqiuIt4aPkoeT+mFMmbdVdnKCwMDF+PxjD1hcFXs8pZiv+h+Aq76QntP
    on:
      appveyor_repo_tag: true
