# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
  - Visual Studio 2022
#  - Ubuntu2204

# Please don't edit it manually, use the `build.bat version` command instead.
version: 0.8.2-build-0{build}

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - sh: nuget locals all -clear

build_script:
  - cmd: build.bat
  - sh: dotnet test -c:release -f:net6.0 tests/Cronos.Tests

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: S4K9NB29VqiuIt4aPkoeT+mFMmbdVdnKCwMDF+PxjD1hcFXs8pZiv+h+Aq76QntP
    on:
      appveyor_repo_tag: true
