# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

os: Visual Studio 2019

version: 0.7.0-build-0{build}

pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - powershell .\build.ps1 --target=Pack
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.snupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: AobFVKZmhZM34uZV2V7jbebMdL9+ZgZ67HzrhBGLf2w9dl70bWx4JVGAteNbbjMR
    on:
      appveyor_repo_tag: true
