# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

os: Visual Studio 2017

version: 0.7.0-build-0{build}

branches:
  only:
    - master
    - dev

pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - powershell .\build.ps1 -Target Pack
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: ngA2/w4mo/D10zK1vfIqEXFk2UzmvynE8QDQVLB3cKDGDkCm12CSA3IlQK2yPIy6
    on:
      appveyor_repo_tag: true
