# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
  - Visual Studio 2022
#  - Ubuntu2204

# Please don't edit it manually, use the `build.bat version` command instead.
version: 0.8.4-build-0{build}

environment:
  SIGNPATH_API_TOKEN:
    secure: J4NQ06YnHkzn0R+ZXz+TGbHHnfsp2KHeWzAeFr3oPKsvZnpkYuZNv5L118BcEx3B

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - ps: Install-Module -Name SignPath
  - sh: nuget locals all -clear

build_script:
  - cmd: build.bat sign
  - sh: dotnet test -c:release -f:net6.0 tests/Cronos.Tests

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: S4K9NB29VqiuIt4aPkoeT+mFMmbdVdnKCwMDF+PxjD1hcFXs8pZiv+h+Aq76QntP
    on:
      appveyor_repo_tag: true
